services:
  - type: web
    name: tycs-line-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:10000"

  - type: worker
    name: tycs-line-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python worker.py"
    schedule: "@hourly"
