services:
  - type: web
    name: tycs-line-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:10000"

  - type: cron
    name: tycs-crawler
    schedule: "*/5 * * * *"    # 台灣時間 08:00
    command: "python worker.py crawler"

  - type: cron
    name: tycs-pusher
    schedule: "0 14 * * *"   # 台灣時間 19:00
    command: "python worker.py push"

