name: Run Crawler Daily

on:
  schedule:
    - cron: '0 10 * * *'  # 台灣時間 18:00
  workflow_dispatch:

jobs:
  crawl-job:
    name: Run Crawler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Check LINE_CHANNEL_ACCESS_TOKEN
        run: |
          if [ -z "$LINE_CHANNEL_ACCESS_TOKEN" ]; then
            echo "ERROR: LINE_CHANNEL_ACCESS_TOKEN is empty!"
            exit 1
          else
            echo "LINE_CHANNEL_ACCESS_TOKEN is set. Length: ${#LINE_CHANNEL_ACCESS_TOKEN}"
          fi
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      - name: Run crawler script
        env:
          GOOGLE_CREDS_B64: ${{ secrets.GOOGLE_CREDS_B64 }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
        run: python worker.py crawler
